<?php
/** @var \Laconica\Analytics\Block\Newsletter\Subscribe $this */

$configs = $this->getConfigHelper();
if (!$configs->isEnabled()) {
    return;
}
?>
<script>
    require(['jquery'], function ($) {
        if (!dataLayer) {
            return;
        }

        let bodyElement = $('body');
        let newsletterFormId = "#newsletter-validate-detail";

        bodyElement.on('click', '.footer-menu .newsletter a', function () {
            dataLayer.push({
                "event": "emailModalTrigger",
            });
        });

        bodyElement.on('submit', newsletterFormId, function (event) {
            event.preventDefault();
            let submitBtn = $(this).find('[type="submit"]');
            $.ajax({
                type: "POST",
                url: "<?php echo $this->getSubscribeUrl(); ?>",
                dataType: "json",
                data: $(this).serialize(),
                beforeSend: function (response) {
                    submitBtn.attr('disabled', 'true');
                },
                success: function (response) {
                    let status = parseInt(response.success);
                    if (status !== 0 && !isNaN(status)) {
                        dataLayer.push({
                            "event": "emailModalSubmit",
                        });
                    }
                    location.reload();
                },
                error: function () {
                    location.reload();
                },
                complete: function () {
                    submitBtn.removeAttr('disabled');
                }
            });

        });
    })
</script>
