<?php
/** @var \Magestore\Storepickup\Block\Wrapper $block */
?>
<script type="text/javascript">
    window.googleSpecialCountry= "<?php echo $this->helper('Magestore\Storepickup\Helper\Data')->getSpecialCountry()?>";
    var select_store_by_map ='<div id="select_store_by_map" ><?php echo __("Select store by map") ?></div>';
    var storepickup_date_box = '<div id="shipping_date_div" class="storepickup-box field required"> Please select Pickup Date/Time to go next step!<br/>'
        + '<label for="shipping_date"><?php echo __("Pickup Date :") ?> </label>'
         + '<input name="shipping_date" style="display:none;" type="text" id="shipping_date" value="" class="input-text required-entry form-control" readonly>'
        + '</div>' +'<br />';
    var storepickup_time_box = '<div id="shipping_time_div" class="storepickup-box field required">'
        + '<label for="shipping_time"><?php echo __("Pickup Time :") ?>  </label>'
        + '<select style="display:none;" id="shipping_time" name="shipping_time" class="validate-select"></select>'
        + '</div>';
    var defaultStore= '<?php echo $block->getSystemConfig()->getDefaultStore() ?>';
    var isDisplayPickuptime= <?php echo $block->getSystemConfig()->isDisplayPickuptime() ?>;
    var storePikcuplatitude="";
    var storePikcuplongitude="";
    //CUSTOM CODE
    var updateTipsUrl = '<?php echo $block->getUrl('storepickup/tips/update');?>';
    var updateTipsMethod = function () {
        require(['jquery', 'jquery/ui'], function($){
            let tips = $('input#tips').val();
            $('.overlay-bg-checkout').show();
            $.ajax({
                method: "GET",
                url: updateTipsUrl,
                data: { tips: tips }
            }).done(function (msg) {
                console.log('updated tips');
                $('.overlay-bg-checkout').hide();
            });

        });
    };
    //END CUSTOM CODE
    window.onload = function() {
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal',
                'Magestore_Storepickup/js/checkout/storepickupcheckout'
            ],
            function(
                $,
                modal
            ) {
                console.log('trololo');
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Choose store by map',
                    buttons: [{
                        text: $.mage.__('Close'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };

                var popup = modal(options, $('#popup-mpdal'));
            }
        );
    };

    window.liststoreJson = <?php echo $block->getListStore() ?>;

</script>

<div id="popup-mpdal" class="storepickup-wrapper col-full" style="display: none;">
    <?php echo $block->getChildHtml('storepickupCheckout.gmapstore') ?>
</div>
<div class="overlay-bg-checkout" style="display: none">
    <img src="<?php echo $block->getViewFileUrl('Magestore_Storepickup::images/ajax-loader.gif') ?>" alt="overlay" />
</div>