<?php
/** @var Laconica\Theme\Block\Html\Gtm $this */
$gtmId = $this->getGtmId();
if($this->isEnabled() && $gtmId): ?>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?php echo $gtmId; ?>"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<?php endif; ?>