<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Laconica\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$relatedProducts = $block->getRelatedProducts();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <ul class="data table additional-attributes" id="product-attribute-specs-table">
            <?php foreach ($_additional as $_data): ?>
                <?php $value = $_helper->productAttribute($_product, $_data['value'], $_data['code']); ?>
                <?php if (!in_array((string)$value, array('N/A', 'No'))) : ?>
                    <li>
                        <span class="bullet">• </span>
                        <?php echo $block->escapeHtml(__($_data['label'])) ?>:
                            <?php /* @escapeNotVerified */
                            echo $value ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if ($relatedProducts && count($relatedProducts->getItems()) > 0) : ?>
                <li>
                    <span>Related Products</span>
                    <span>
                        <?php foreach ($relatedProducts->getItems() as $relatedProduct) : ?>
                            <a href="<?= $relatedProduct->getProductUrl() ?>"><?= $relatedProduct->getAttributeText('year') ?></a>
                        <?php endforeach; ?>
                    </span>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>
