<?php
/** @var $block Laconica\Catalog\Block\Product\View\Rating */

$product = $block->getProduct();
for ($i = 1; $i < 5; $i++) :
    $rate = $product->getData("rate$i");
    $pub = $product->getData("pub$i");
    $pubdesc = $product->getData("pubdesc$i");
?>
    <?php if ($rate && $rate != "0"): ?>
        <h3><?= $rate ?> Points</h3>
        <h3><?= $pub ?></h3>
        <p><?= $pubdesc ?></p>
     <?php endif; ?>
<?php endfor;
