<?php
/** @var Magento\Framework\View\Element\Template $block */
$product = $block->getProduct();
if ($product) :
    if ($product->getTypeId() == 'configurable') {
        $children = $product->getTypeInstance()->getUsedProducts($product);
    } else {
        $children = [$product];
    }
    foreach ($children as $child) :
        if ($child->getData('rate1') && $child->getData('pub1')) : ?>
            <div>
                <p style="font-weight: bold">
                    <?= $child->getData('rate1'); ?> <?= $child->getData('pub1'); ?>
                </p>
            </div>
            <?php break;
        endif;
    endforeach;
endif; ?>

