<!DOCTYPE html>
<html>
<body>
    <form action="<?php echo $block->getUrl('migratedata/migratedata_supplier/migrate'); ?>" method="post" enctype="multipart/form-data">
        Select supplier data file to upload:
        <input type="file" name="migrate_supplier" id="migrate_supplier">
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey(); ?>"
        <button type="submit">
        
        </button>
        <button id="start" title="Submit" type="submit" class="action- scalable save primary" data-ui-id="start-button">
            <span>Submit</span>
        </button>
    </form>
</body>
</html>